# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LAB1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 350)
        MainWindow.setMinimumSize(QtCore.QSize(750, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.text_input_verify = QtWidgets.QTextEdit(self.centralwidget)
        self.text_input_verify.setObjectName("text_input_verify")
        self.verticalLayout_2.addWidget(self.text_input_verify)
        self.signature_input = QtWidgets.QLineEdit(self.centralwidget)
        self.signature_input.setObjectName("signature_input")
        self.verticalLayout_2.addWidget(self.signature_input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_import_signature = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import_signature.setObjectName("btn_import_sign")
        self.horizontalLayout.addWidget(self.btn_import_signature)
        self.btn_paste_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_paste_sign.setObjectName("btn_paste_sign")
        self.horizontalLayout.addWidget(self.btn_paste_sign)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.btn_verify_from_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify_from_text.setObjectName("btn_verify_from_text")
        self.verticalLayout_2.addWidget(self.btn_verify_from_text)
        self.btn_verify_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify_from_file.setObjectName("btn_verify_from_file")
        self.verticalLayout_2.addWidget(self.btn_verify_from_file)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.text_input_create = QtWidgets.QTextEdit(self.centralwidget)
        self.text_input_create.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text_input_create.setObjectName("text_input_create")
        self.verticalLayout.addWidget(self.text_input_create)
        self.signature_output = QtWidgets.QLineEdit(self.centralwidget)
        self.signature_output.setEnabled(True)
        self.signature_output.setMouseTracking(True)
        self.signature_output.setObjectName("signature_output")
        self.verticalLayout.addWidget(self.signature_output)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_copy_signature = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy_signature.setObjectName("btn_copy_signature")
        self.horizontalLayout_2.addWidget(self.btn_copy_signature)
        self.btn_export_signature = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export_signature.setObjectName("btn_export_signature")
        self.horizontalLayout_2.addWidget(self.btn_export_signature)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_create_from_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create_from_text.setObjectName("btn_create_from_text")
        self.verticalLayout.addWidget(self.btn_create_from_text)
        self.btn_create_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create_from_file.setObjectName("btn_create_from_file")
        self.verticalLayout.addWidget(self.btn_create_from_file)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Digital Signature (LAB1)"))
        self.label_3.setText(_translate("MainWindow", "Verify Signatue"))
        self.text_input_verify.setPlaceholderText(_translate("MainWindow", "Enter Text to Verify"))
        self.signature_input.setPlaceholderText(_translate("MainWindow", "Enter Digital Signature or Use Button \"Import Signature\""))
        self.btn_import_signature.setText(_translate("MainWindow", "Import Signature from File"))
        self.btn_paste_sign.setText(_translate("MainWindow", "Paste from Clipboard"))
        self.btn_verify_from_text.setText(_translate("MainWindow", "Verify Digital Signature from Input"))
        self.btn_verify_from_file.setText(_translate("MainWindow", "Verify Digital Signature from File"))
        self.label_2.setText(_translate("MainWindow", "Create Signature"))
        self.text_input_create.setPlaceholderText(_translate("MainWindow", "Enter Text to Sign"))
        self.signature_output.setPlaceholderText(_translate("MainWindow", "Digital Signature will Appear Here"))
        self.btn_copy_signature.setText(_translate("MainWindow", "Copy Digital Signature"))
        self.btn_export_signature.setText(_translate("MainWindow", "Export Signature"))
        self.btn_create_from_text.setText(_translate("MainWindow", "Create Digital Signatue from Text Input"))
        self.btn_create_from_file.setText(_translate("MainWindow", "Create Digital Signatue from File"))
        self.label.setText(_translate("MainWindow", "Created by MC Лёша & DJ Mitch"))

